services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-books}
      POSTGRES_USER: ${POSTGRES_USER:-books}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-books}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-books} -d ${POSTGRES_DB:-books}"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    command: ["/app/entrypoint.sh"]
#   command:  ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"] #Activar para  produccion
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
