# Generated by Django 5.2.5 on 2025-08-21 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID único')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='books_autho_last_na_640239_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID único')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Páginas')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio')),
                ('language', models.CharField(default='Español', max_length=30, verbose_name='Idioma')),
                ('literary_genre', models.CharField(max_length=50, verbose_name='Género literario')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen')),
                ('authors', models.ManyToManyField(related_name='books', to='books_authors.author', verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='books_autho_title_bce8fe_idx')],
            },
        ),
    ]
